global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'coreweave-demo'
    environment: 'development'

alerting:
  alertmanagers:
    - static_configs:
        - targets: 
          - 'alertmanager:9093'  

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          instance: 'prometheus-server'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'monitoring-host'
          role: 'infrastructure'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          instance: 'docker-host'
          role: 'container-monitor'

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          app: 'nginx'
          tier: 'frontend'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          app: 'redis'
          tier: 'cache'

  - job_name: 'python-app'
    static_configs:
      - targets: ['python-app:8000']
        labels:
          app: 'python-api'
          tier: 'application'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          app: 'postgres'
          tier: 'database'

  - job_name: 'gpu-simulator'
    static_configs:
      - targets: ['gpu-simulator:9400']
        labels:
          component: 'gpu'
          environment: 'simulation'

  - job_name: 'ml-simulator'
    static_configs:
      - targets: ['ml-simulator:9500']
        labels:
          component: 'ml'
          environment: 'simulation'
